### ISSUE TITLE
VAT percentage are 100 times to high

### ISSUE THREAD

**Issue by Schrank** [goodscloud/goodscloud-magento#7]
Somewhere is a . instead of a , or something like this. Need to investigate and check

**Comment by glyphobet** [comment]
This is actually a data problem. The vat_rate column supports rates over 100%: `0.19` is 19%, `0.09` is 9%, `9.00` would be 900%.

This is not really documented, sorry. But I think you should check how the VAT rates are created by the Magento plugin.

**Comment by Schrank** [comment]
ah damn :-)

ok, will fix
